import HeroSection from "@/components/HeroSection";
import MarketUpdate from "@/components/MarketUpdate";
import Navbar from "@/components/Navbar";
import TrendingCoins from "@/components/TrendingCoins";
import Head from "next/head";
import Footer from "@/components/Footer";
import useSWR, { Fetcher } from "swr";
import axios from "axios";

import { createContext } from "react";
import type { detailedCoin } from "@/types/Types";
export const CoinsContext = createContext<detailedCoin | undefined>(null);
const fetcher: Fetcher<detailedCoin, string> = (url: string) =>
  axios.get(url).then((res) => res.data);
export default function Home() {
  const { data, isLoading, error } = useSWR(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=gecko_desc&per_page=7&page=1&sparkline=false",
    fetcher,
    {
      refreshInterval: 60000,
    }
  );

  if (isLoading) return <div>LOADING...</div>;
  if (error) return <div>ERROR</div>;
  return (
    <>
      <Head>
        <title>CryptoCap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <CoinsContext.Provider value={data}>
        <Navbar />
        <HeroSection />
        <TrendingCoins />
        <MarketUpdate />
        <Footer />
      </CoinsContext.Provider>
    </>
  );
}
